#CPPFLAGS	= -std=c++11 -I/homes/jwallwork/software/adol-c/ADOL-C-2.6.0/build/include
CPPFLAGS	= -std=c++11 -I/${ADOLC_HOME}/build/include
CFLAGS		=
EXAMPLESC	= ex1.cpp

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
